#!/bin/bash
sheet=7

cabal build
error_level=$?

for n in 1 2 3 4 5; do
    task_id="Task$sheet$n"
    [ -f "./$task_id" ] && rm -f "./$task_id"
    [ -f "./dist-newstyle/build/x86_64-linux/ghc-9.4.7/sheet$sheet-0.1.0.0/x/$task_id/build/$task_id/$task_id" ] && echo ">>> $task_id" && cp "./dist-newstyle/build/x86_64-linux/ghc-9.4.7/sheet$sheet-0.1.0.0/x/$task_id/build/$task_id/$task_id" "./$task_id"
done

exit $error_level
